{% set name = "xyz" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a29590b61bf5d192a7e969379c58fea1fc3eae96582bfdd479aba0aa50b79a8c

build:
  number: 0
  noarch: python
  entry_points:
    - xyz=xyz.xyz:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - tqdm >=4.38.0
    - pandas >=1.0.1
    - networkx >=2.8
    - seaborn >=0.11.2
    - matplotlib >=3.5.2

test:
  imports:
    - xyz
  commands:
    - pip check
    - xyz --version
  requires:
    - pip

about:
  home: https://github.com/fabio-cumbo/xyz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: xyz
  description: |
    A novel method for assessing and measuring homophily in networks through second-order statistics.

extra:
  recipe-maintainers:
    - fabio-cumbo
