name: honto
owner: fabio
categories:
  - Visualization
description: honto
long_description: |
  A novel method for assessing and measuring homophily in networks.
remote_repository_url: https://github.com/fabio-cumbo/honto
homepage_url: https://github.com/fabio-cumbo/honto
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  descriptor_template: "Wrapper for {{ tool_name }}"
